riff.ui.global.factory = {
	idleEllipsis : 32,
	titleEllipsis : 60,
	summaryEllipsis : 75,
	imgSummaryEllipsis : 40,
}

var langEN = [
	"English",
	"Korean",
	"French",
	"Done",
	"Loading...",
	"Component",
	"Event",
	"Ajax",
	"Device Variation",
	"Multi Language",
	"Riff's Components",
	"Touch Events",
	"Ajax Processing Module",
	"Support various resolutions",
	"Easy translation",
	"News RSS Feed",
	"Public RSS feed of Yahoo! News"	
];
var langFR = [
	"Anglais", 
	"Coréen", 
	"Français",
	"fait",
	"de chargement...",
	"Composante",
	"Evénement",
	"Ajax",
	"La variation de périphérique",
	"Multi-langue",
	"Riff Composants",
	"Evénements tactile",
	"Ajax module de traitement",
	"Soutien de diverses résolutions",
	"facile de traduction",
	"Nouvelles rss feed",
	"Public RSS feed of Yahoo! News",
]
var langKO = [
	"영어",
	"한국어",
	"프랑스어",
	"완료",
	"로딩 중...",
	"컴포넌트",
	"이벤트",
	"Ajax 통신",
	"다양한 단말 지원",
	"다국어",
	"Riff의 컴포넌트",
	"터치 이벤트들",
	"Ajax 통신모듈",
	"다양한 해상도 지원",
	"쉬운 번역",
	"RSS 뉴스피드",
	"공개된 야후!뉴스 피드"
]